### ISSUE TITLE
does not work with mockito 2.0 (as of byte buddy)

### ISSUE THREAD

**Issue by dpreussler** [dpreussler/kotlin-testrunner#10]
when changing the test to use mockito 2.0 the executation fails.
testCompile 'org.mockito:mockito-core:2.0.52-beta'

de.jodamob.kotlin.testrunner.tests.TestWithRunnerWithoutConfiguration > should_open_class_in_same_package FAILED
    org.mockito.exceptions.base.MockitoException at TestWithRunnerWithoutConfiguration.kt:16
        Caused by: java.lang.IllegalStateException at TestWithRunnerWithoutConfiguration.kt:16
            Caused by: javassist.CannotCompileException at TestWithRunnerWithoutConfiguration.kt:16
                Caused by: java.lang.LinkageError at TestWithRunnerWithoutConfiguration.kt:16

**Comment by dpreussler** [comment]
@uKL do you have an idea here?
happens even when I run the single test on command line (with gradle wrapper)

**Comment by uKL** [comment]
Do you use gradle daemon? I had similar issue but I think restarting daemon helped. 

`gradle --stop`

Maybe it has something to do with bytebuddy? How do you use it?

**Comment by dpreussler** [comment]
demon not in use.

Asked myself the same if its related to bytebuddy.. not sure where this comes from, guess needs some investigation time :)

**Comment by dpreussler** [comment]
PowerMock had the same issue:
https://github.com/jayway/powermock/issues/579

**Comment by dpreussler** [comment]
does not happen in 2.0.82-beta, closing for now
