### ISSUE TITLE
NoMoreFinalsClassLoader is too abusive

### ISSUE THREAD

**Issue by uKL** [dpreussler/kotlin-testrunner#4]
IMO it may be better to specify which classes should be opened rather than open them all within the classloader. It may cause issues with some libraries (groovy, spock, etc.)

**Comment by dpreussler** [comment]
agree, would be at least good to have more exclusive filters
But when specifying single classes then you could also use PowerMock as this is what they do

**Comment by uKL** [comment]
I'll prepare a Pull Request and you'll take a look, ok?

**Comment by dpreussler** [comment]
sure! :)
